import '../../data/models/account.dart';

List<Account> presetAccounts = [
  // ============ 资产类 Assets ============
  Account(id: '1001', nameZh: '库存现金', nameEn: 'Cash on Hand', nameKo: '현금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true, openingBalance: 10000,
      explanationZh: '企业存放在保险柜中的货币资金。', explanationEn: 'Currency held by the business in its safe.', explanationKo: '기업이 금고에 보관하는 통화.'),
  Account(id: '1002', nameZh: '银行存款', nameEn: 'Bank Deposit', nameKo: '은행예금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true, openingBalance: 100000,
      explanationZh: '企业存放在银行账户中的资金。', explanationEn: 'Funds held in the bank account.', explanationKo: '은행 계좌에 보관된 자금.'),
  Account(id: '1012', nameZh: '其他货币资金', nameEn: 'Other Monetary Assets', nameKo: '기타 화폐 자산', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1101', nameZh: '交易性金融资产', nameEn: 'Trading Financial Assets', nameKo: '매매금융자산', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1121', nameZh: '应收票据', nameEn: 'Notes Receivable', nameKo: '받을어음', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1122', nameZh: '应收账款', nameEn: 'Accounts Receivable', nameKo: '외상매출금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1123', nameZh: '预付账款', nameEn: 'Prepaid Accounts', nameKo: '선급금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1131', nameZh: '应收股利', nameEn: 'Dividends Receivable', nameKo: '미수배당금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1132', nameZh: '应收利息', nameEn: 'Interest Receivable', nameKo: '미수이자', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1221', nameZh: '其他应收款', nameEn: 'Other Receivables', nameKo: '기타 미수금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1231', nameZh: '坏账准备', nameEn: 'Bad Debt Provision', nameKo: '대손충당금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true, openingBalance: 0,
      explanationZh: '应收账款中预计无法收回的金额。坏账准备是应收账款的备抵科目。', explanationEn: 'Estimated uncollectible amounts in accounts receivable. This is a contra-asset account.', explanationKo: '회수 불가능할 것으로 예상되는 외상매출금. 자산의 차감 계정입니다.'),
  Account(id: '1401', nameZh: '材料采购', nameEn: 'Material Procurement', nameKo: '재료구매', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1403', nameZh: '原材料', nameEn: 'Raw Materials', nameKo: '원재료', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true, openingBalance: 50000),
  Account(id: '1405', nameZh: '库存商品', nameEn: 'Finished Goods', nameKo: '제품', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true, openingBalance: 80000),
  Account(id: '1411', nameZh: '周转材料', nameEn: 'Revolving Materials', nameKo: '회전자재', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1471', nameZh: '存货跌价准备', nameEn: 'Inventory Write-down', nameKo: '재고평가손실충당금', category: 'asset', subCategory: 'current_asset', type: 1, isSystem: true),
  Account(id: '1501', nameZh: '持有至到期投资', nameEn: 'Held-to-Maturity Investments', nameKo: '만기보유투자', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1511', nameZh: '长期股权投资', nameEn: 'Long-term Equity Investment', nameKo: '장기지분투자', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1601', nameZh: '固定资产', nameEn: 'Fixed Assets', nameKo: '고정자산', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true, openingBalance: 200000,
      explanationZh: '企业为生产商品、提供劳务或经营管理而持有的、使用寿命超过一个会计年度的有形资产。', explanationEn: 'Tangible assets held for producing goods, providing services, or administrative purposes with a useful life exceeding one year.', explanationKo: '상품 생산, 용역 제공 또는 관리 목적으로 보유하는 내용연수 1년 이상의 유형자산.'),
  Account(id: '1602', nameZh: '累计折旧', nameEn: 'Accumulated Depreciation', nameKo: '감가상각누계액', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true, openingBalance: -20000,
      explanationZh: '固定资产因使用损耗而累计减少的价值。是固定资产的备抵科目。', explanationEn: 'The cumulative reduction in value of fixed assets due to usage. This is a contra-asset account.', explanationKo: '사용에 따른 고정자산 가치의 누적 감소액. 자산의 차감 계정입니다.'),
  Account(id: '1604', nameZh: '在建工程', nameEn: 'Construction in Progress', nameKo: '건설중인자산', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1606', nameZh: '固定资产清理', nameEn: 'Fixed Asset Disposal', nameKo: '고정자산처분', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1701', nameZh: '无形资产', nameEn: 'Intangible Assets', nameKo: '무형자산', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1702', nameZh: '累计摊销', nameEn: 'Accumulated Amortization', nameKo: '무형자산상각누계액', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1801', nameZh: '长期待摊费用', nameEn: 'Long-term Prepaid Expenses', nameKo: '장기선급비용', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),
  Account(id: '1901', nameZh: '待处理财产损溢', nameEn: 'Pending Property Loss/Gain', nameKo: '미처리재산손익', category: 'asset', subCategory: 'noncurrent_asset', type: 1, isSystem: true),

  // ============ 负债类 Liabilities ============
  Account(id: '2001', nameZh: '短期借款', nameEn: 'Short-term Loans', nameKo: '단기차입금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2201', nameZh: '应付票据', nameEn: 'Notes Payable', nameKo: '지급어음', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2202', nameZh: '应付账款', nameEn: 'Accounts Payable', nameKo: '외상매입금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true, openingBalance: 30000),
  Account(id: '2203', nameZh: '预收账款', nameEn: 'Advances from Customers', nameKo: '선수금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2211', nameZh: '应付职工薪酬', nameEn: 'Payroll Payable', nameKo: '미지급임금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2221', nameZh: '应交税费', nameEn: 'Tax Payable', nameKo: '미지급세금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2231', nameZh: '应付利息', nameEn: 'Interest Payable', nameKo: '미지급이자', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2232', nameZh: '应付股利', nameEn: 'Dividends Payable', nameKo: '미지급배당금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2241', nameZh: '其他应付款', nameEn: 'Other Payables', nameKo: '기타 미지급금', category: 'liability', subCategory: 'current_liability', type: 2, isSystem: true),
  Account(id: '2501', nameZh: '长期借款', nameEn: 'Long-term Loans', nameKo: '장기차입금', category: 'liability', subCategory: 'noncurrent_liability', type: 2, isSystem: true),
  Account(id: '2502', nameZh: '应付债券', nameEn: 'Bonds Payable', nameKo: '사채', category: 'liability', subCategory: 'noncurrent_liability', type: 2, isSystem: true),
  Account(id: '2701', nameZh: '长期应付款', nameEn: 'Long-term Payables', nameKo: '장기미지급금', category: 'liability', subCategory: 'noncurrent_liability', type: 2, isSystem: true),

  // ============ 所有者权益类 Owner's Equity ============
  Account(id: '3001', nameZh: '实收资本', nameEn: 'Paid-in Capital', nameKo: '자본금', category: 'equity', subCategory: 'equity', type: 3, isSystem: true, openingBalance: 390000,
      explanationZh: '投资者实际投入企业的资本。', explanationEn: 'Capital actually invested by the owners.', explanationKo: '투자자가 실제로 기업에 투자한 자본.'),
  Account(id: '3002', nameZh: '资本公积', nameEn: 'Capital Reserve', nameKo: '자본잉여금', category: 'equity', subCategory: 'equity', type: 3, isSystem: true),
  Account(id: '3101', nameZh: '盈余公积', nameEn: 'Surplus Reserve', nameKo: '이익잉여금', category: 'equity', subCategory: 'equity', type: 3, isSystem: true),
  Account(id: '3103', nameZh: '本年利润', nameEn: 'Current Year Profit', nameKo: '당기순이익', category: 'equity', subCategory: 'equity', type: 3, isSystem: true,
      explanationZh: '企业在本年度累计实现的净利润（或亏损）。', explanationEn: 'The cumulative net profit (or loss) realized in the current year.', explanationKo: '당해 연도 누적 순이익(또는 손실).'),
  Account(id: '3104', nameZh: '利润分配', nameEn: 'Profit Distribution', nameKo: '이익처분', category: 'equity', subCategory: 'equity', type: 3, isSystem: true),

  // ============ 成本类 Costs ============
  Account(id: '4001', nameZh: '生产成本', nameEn: 'Production Cost', nameKo: '생산원가', category: 'cost', subCategory: 'cost', type: 4, isSystem: true,
      explanationZh: '生产产品过程中发生的直接材料、直接人工和制造费用。', explanationEn: 'Direct materials, direct labor, and manufacturing overhead incurred in production.', explanationKo: '제품 생산 과정에서 발생하는 직접재료비, 직접노무비 및 제조간접비.'),
  Account(id: '4101', nameZh: '制造费用', nameEn: 'Manufacturing Overhead', nameKo: '제조간접비', category: 'cost', subCategory: 'cost', type: 4, isSystem: true),

  // ============ 损益类 - 收入 P&L - Revenue ============
  Account(id: '5001', nameZh: '主营业务收入', nameEn: 'Main Operating Revenue', nameKo: '주된영업수익', category: 'pl', subCategory: 'income', type: 5, isSystem: true,
      explanationZh: '企业日常经营活动产生的收入。', explanationEn: 'Revenue generated from the main operating activities.', explanationKo: '주된 영업 활동에서 발생하는 수익.'),
  Account(id: '5051', nameZh: '其他业务收入', nameEn: 'Other Operating Revenue', nameKo: '기타영업수익', category: 'pl', subCategory: 'income', type: 5, isSystem: true),
  Account(id: '5101', nameZh: '公允价值变动损益', nameEn: 'Fair Value Change Gain', nameKo: '공정가치변동이익', category: 'pl', subCategory: 'income', type: 5, isSystem: true),
  Account(id: '5201', nameZh: '投资收益', nameEn: 'Investment Income', nameKo: '투자수익', category: 'pl', subCategory: 'income', type: 5, isSystem: true),
  Account(id: '5301', nameZh: '营业外收入', nameEn: 'Non-operating Income', nameKo: '영업외수익', category: 'pl', subCategory: 'income', type: 5, isSystem: true),

  // ============ 损益类 - 费用 P&L - Expense ============
  Account(id: '5401', nameZh: '主营业务成本', nameEn: 'Main Operating Cost', nameKo: '주된영업원가', category: 'pl', subCategory: 'expense', type: 6, isSystem: true,
      explanationZh: '与主营业务收入相配比的成本。', explanationEn: 'Costs matched against main operating revenue.', explanationKo: '주된 영업 수익에 대응하는 원가.'),
  Account(id: '5402', nameZh: '其他业务成本', nameEn: 'Other Operating Cost', nameKo: '기타영업원가', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5403', nameZh: '税金及附加', nameEn: 'Taxes & Surcharges', nameKo: '세금및부가세', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5501', nameZh: '销售费用', nameEn: 'Selling Expenses', nameKo: '판매비', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5502', nameZh: '管理费用', nameEn: 'Administrative Expenses', nameKo: '관리비', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5503', nameZh: '财务费用', nameEn: 'Financial Expenses', nameKo: '재무비용', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5601', nameZh: '资产减值损失', nameEn: 'Asset Impairment Loss', nameKo: '자산손상차손', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5701', nameZh: '营业外支出', nameEn: 'Non-operating Expenses', nameKo: '영업외비용', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
  Account(id: '5801', nameZh: '所得税费用', nameEn: 'Income Tax Expense', nameKo: '소득세비용', category: 'pl', subCategory: 'expense', type: 6, isSystem: true),
];
