// Syncs version.json -> pubspec.yaml, fdroid yml, and generates app_version.dart.
//
// Usage:
//   dart run scripts/sync_version.dart

import 'dart:convert';
import 'dart:io';

const versionFile = 'version.json';
const pubspecFile = 'pubspec.yaml';
const fdroidFile = 'fdroid/com.yosvu.ledgerlearn.ledgerlearn.yml';
const dartOutput = 'lib/app/config/app_version.dart';

void main() {
  // 1. Read version.json
  final versionJson = File(versionFile);
  if (!versionJson.existsSync()) {
    stderr.writeln('Error: $versionFile not found.');
    exit(1);
  }

  final Map<String, dynamic> version;
  try {
    version = json.decode(versionJson.readAsStringSync()) as Map<String, dynamic>;
  } catch (e) {
    stderr.writeln('Error parsing $versionFile: $e');
    exit(1);
  }

  final ver = version['version'] as String;
  final code = version['version_code'] as int;

  stdout.writeln('Syncing version $ver+$code from $versionFile...');

  // 2. Update pubspec.yaml
  _updatePubspec(ver, code);

  // 3. Update fdroid yml
  _updateFdroid(ver, code);

  // 4. Generate app_version.dart
  _generateDartFile(ver, code);

  stdout.writeln('Done. Version $ver+$code synced to all targets.');
}

void _updatePubspec(String version, int code) {
  final file = File(pubspecFile);
  var content = file.readAsStringSync();
  final pattern = RegExp(r'^version:\s*.*$', multiLine: true);
  final replacement = 'version: $version+$code';

  if (pattern.hasMatch(content)) {
    content = content.replaceAll(pattern, replacement);
  } else {
    stderr.writeln('Warning: No version line found in $pubspecFile');
  }

  file.writeAsStringSync(content);
  stdout.writeln('  Updated: $pubspecFile');
}

void _updateFdroid(String version, int code) {
  final file = File(fdroidFile);
  if (!file.existsSync()) {
    stderr.writeln('Warning: $fdroidFile not found, skipping.');
    return;
  }

  var content = file.readAsStringSync();

  content = content.replaceAll(
    RegExp(r'^CurrentVersion:\s*.*$', multiLine: true),
    'CurrentVersion: $version',
  );
  content = content.replaceAll(
    RegExp(r'^CurrentVersionCode:\s*.*$', multiLine: true),
    'CurrentVersionCode: $code',
  );

  file.writeAsStringSync(content);
  stdout.writeln('  Updated: $fdroidFile');
}

void _generateDartFile(String version, int code) {
  final dir = Directory('lib/app/config');
  if (!dir.existsSync()) {
    dir.createSync(recursive: true);
  }

  final content = '''
/// Auto-generated by scripts/sync_version.dart — do not edit by hand.
const String appVersion = '$version';
const int appVersionCode = $code;
''';

  File(dartOutput).writeAsStringSync(content);
  stdout.writeln('  Generated: $dartOutput');
}
